### ISSUE TITLE
[feature] Add the ability to log ULX commands in another Discord text channel

### ISSUE THREAD

**Issue by keganpowers34** [Derpius/pythonsourceserverdiscordbot#7]
**Feature description**
add an option to allow logging of ulx commands in a text channel

**Possible implementation**
check if a player did a ulx command and make an embed text saying who did it when and what command was it

**Comment by Derpius** [comment]
Due to the way the actual bot is structured (even if I implemented relaying to multiple channels), it would have to display to the same channel as relay chat.  

However I could maintain the game agnostic structure, while implementing ULX commands being displayed in Disccord, by adding a "custom" type to the HTTP API so an individual relay client (atm only the GMod one) can send custom messages to the bot (in this case, ULX command events).

**Comment by Derpius** [comment]
`custom` type added to the relay server API taking a plaintext `body` argument to be printed directly to discord as a message body.  
Only thing left to do is actually create an extension to the GMOD client that uses this new `custom` payload type to display messages to discord when a ULX command is triggered.  

Due to this requiring manually defining formatting for a plethora of commands, it's on low priority for now (although I'll probably implement commonly used commands like `!god`, `!kick`, etc. anyway)

**Comment by Derpius** [comment]
`DiscordRelay.CachePost` has been a global in the GMod client for quite a bit now, which (along with the hooks) allows extending the functionality of the relay with something like this on a game-by-game basis.
